-- =============================================================================
-- Migration 015: Update create_farm_and_membership RPC for address fields
-- =============================================================================
-- Replaces the create_farm_and_membership function to accept address fields
-- instead of the optional WHIM number parameter.
--
-- BREAKING CHANGE: The old function signature (p_farm_name, p_whim_number) is
-- removed and replaced with (p_farm_name, p_street_address, p_city, p_state, p_zip_code).
-- =============================================================================

-- Drop the old function signature first (required because PostgreSQL uses overloading)
DROP FUNCTION IF EXISTS create_farm_and_membership(TEXT, TEXT);

CREATE OR REPLACE FUNCTION create_farm_and_membership(
    p_farm_name TEXT,
    p_street_address TEXT,
    p_city TEXT,
    p_state TEXT,
    p_zip_code TEXT
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_user_id UUID;
    v_farm_id UUID;
BEGIN
    -- Get the current user's ID
    v_user_id := auth.uid();

    -- Verify user is authenticated
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'Not authenticated';
    END IF;

    -- Validate input lengths (prevent DoS via large strings)
    IF length(p_farm_name) > 255 THEN
        RAISE EXCEPTION 'Farm name too long (max 255 characters)';
    END IF;
    IF length(p_street_address) > 500 THEN
        RAISE EXCEPTION 'Street address too long (max 500 characters)';
    END IF;
    IF length(p_city) > 100 THEN
        RAISE EXCEPTION 'City name too long (max 100 characters)';
    END IF;
    IF length(p_state) > 2 THEN
        RAISE EXCEPTION 'State must be a 2-letter abbreviation';
    END IF;
    IF length(p_zip_code) > 10 THEN
        RAISE EXCEPTION 'ZIP code too long (max 10 characters)';
    END IF;

    -- Validate required fields are not empty
    IF trim(p_farm_name) = '' THEN
        RAISE EXCEPTION 'Farm name is required';
    END IF;
    IF trim(p_street_address) = '' THEN
        RAISE EXCEPTION 'Street address is required';
    END IF;
    IF trim(p_city) = '' THEN
        RAISE EXCEPTION 'City is required';
    END IF;
    IF trim(p_state) = '' THEN
        RAISE EXCEPTION 'State is required';
    END IF;
    IF trim(p_zip_code) = '' THEN
        RAISE EXCEPTION 'ZIP code is required';
    END IF;

    -- Create the farm with address fields (trimmed)
    -- Note: invite_code is auto-generated by the set_invite_code trigger from migration 001
    INSERT INTO farms (name, street_address, city, state, zip_code)
    VALUES (trim(p_farm_name), trim(p_street_address), trim(p_city), trim(p_state), trim(p_zip_code))
    RETURNING id INTO v_farm_id;

    -- Create farm membership with owner role
    INSERT INTO farm_members (farm_id, user_id, role)
    VALUES (v_farm_id, v_user_id, 'owner');

    RETURN v_farm_id;
END;
$$;

COMMENT ON FUNCTION create_farm_and_membership(TEXT, TEXT, TEXT, TEXT, TEXT) IS 'Atomically creates a farm with address fields and adds the calling user as owner';
